# Generated by Django 4.1.1 on 2022-10-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
