# Generated by Django 4.1.1 on 2022-10-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_shortlinkstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='expiration_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
