# Generated by Django 4.1.1 on 2022-10-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_shortlink_expiration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='max_clicks',
            field=models.IntegerField(default=5),
        ),
    ]
